spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: mycloud-config-dept-client
info:
  app.name: weir-MyCloud
  company.name: www.weir.com 
  build.artifactId: $project.artifactId$
  build.version: $project.version$ 
eureka: 
  client:
    service-url:
       defaultZone: http://edmin:123456@weir.com:7001/eureka #设置客户端链接注册中心的地址
  instance:
    instance-id: weir-dept-01.com #Eureka注册实例的id(名称)
    prefer-ip-address: true #设置使用主机的ip地址显示
security:
  sessions: stateless
  basic:
    enabled: true     #开启security的服务
  user:
    name: admin       #认证用户
    password: 123456  #认证密码
mybatis:
  config-location: classpath:SqlMapConfig.xml # mybatis配置文件所在路径
  type-aliases-package: com.weir.mycloud.vo   # 定义所有操作类的别名所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml       #定义Mapper文件所在的位置

spring:
  messages:
    basename: i18n/Messages,i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver        # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/db_springcloud_01 # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                                  # 数据库连接密码
    filters: stat,wall,log4j 
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  application:
    name: mycloud-provider-dept-8001                #微服务的名称（便于日后的负载均衡） 
---
server:
  port: 8001
spring:
  profiles: beta
  application:
    name: mycloud-config-dept-client
info:
  app.name: weir-MyCloud
  company.name: www.weir.com 
  build.artifactId: $project.artifactId$
  build.version: $project.version$ 
eureka: 
  client:
    service-url:
       defaultZone: http://edmin:123456@weir.com:7001/eureka #设置客户端链接注册中心的地址
  instance:
    instance-id: weir-dept-01.com #Eureka注册实例的id(名称)
    prefer-ip-address: true #设置使用主机的ip地址显示
security:
  sessions: stateless
  basic:
    enabled: true     #开启security的服务
  user:
    name: admin       #认证用户
    password: 123456  #认证密码
mybatis:
  config-location: classpath:SqlMapConfig.xml # mybatis配置文件所在路径
  type-aliases-package: com.weir.mycloud.vo   # 定义所有操作类的别名所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml       #定义Mapper文件所在的位置

spring:
  messages:
    basename: i18n/Messages,i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver        # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/db_springcloud_01 # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                                  # 数据库连接密码
    filters: stat,wall,log4j 
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  application:
    name: mycloud-provider-dept-8001                #微服务的名称（便于日后的负载均衡） 