spring:
  profiles:
    active:
      - dev
---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: mycloud-config-eureka-client
security:
  basic: 
    enabled: true
  user:
    name: edmin
    password: 123456
    
eureka:
  client:
    service-url: 
      defaultZone: http://edmin:123456@weir.com:7001/eureka #设置客户端链接注册中心的地址
    register-with-eureka: false   #当前微服务不注册到服务中
  server:
    a-s-g-cache-expiry-timeout-ms: 1000  # 设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
  instance:
    hostname: weir.com 
---
server:
  port: 7001
spring:
  profiles: beta
  application:
    name: mycloud-config-eureka-client
security:
  basic: 
    enabled: true
  user:
    name: edmin
    password: 123456
    
eureka:
  client:
    service-url: 
      defaultZone: http://edmin:123456@weir.com:7001/eureka #设置客户端链接注册中心的地址
    register-with-eureka: false   #当前微服务不注册到服务中
  server:
    a-s-g-cache-expiry-timeout-ms: 1000  # 设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
  instance:
    hostname: weir.com 